### ISSUE TITLE
[Feature Request] Support pnpm v9

### ISSUE THREAD

**Issue by tuanphamcybozu** [cybozu/license-manager#9]
## Why
- pnpm has released version 9, which has many major and minor changes from version 8.
Ref: https://github.com/pnpm/pnpm/releases/tag/v9.0.0

- `@cybozu/license-manager` is currently not support `pnpm` v9. 

- This incompatibility has a direct impact on projects using `@cybozu/license-manager`. Attempting to upgrade `pnpm` to v9 results in a failed GitHub actions job, specifically related to the `analyze` and `extract` functions.

## What
- Make `@cybozu/license-manager` support `pnpm` v9. So that project using `@cybozu/license-manager` can upgrade `pnpm` without any concerns.

## Reproduce
- _Log output:_
Ref: https://github.com/kintone/cli-kintone/actions/runs/9448860916/job/26023788533

```
Run pnpm license:analyze
  pnpm license:analyze
  pnpm license:extract
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

> @kintone/cli-kintone@1.10.13 license:analyze /home/runner/work/cli-kintone/cli-kintone
> license-manager analyze -c license-manager.config.js

🔎 Analyzing dependencies...
💡 Detected license-manager.config.js
✅ All dependencies confirmed

> @kintone/cli-kintone@1.10.13 license:extract /home/runner/work/cli-kintone/cli-kintone
> license-manager extract -c license-manager.config.js

🔪 Extract licenses...
💡 Detected license-manager.config.js
/home/runner/work/cli-kintone/cli-kintone/node_modules/.pnpm/@cybozu+license-manager@1.[2](https://github.com/kintone/cli-kintone/actions/runs/9448860916/job/26023788533#step:7:2).1/node_modules/@cybozu/license-manager/dist/functions/getLicenseText.js:14
        throw new Error("invalid dep: " + dep);
              ^

Error: invalid dep: [object Object]
    at getLicenseText (/home/runner/work/cli-kintone/cli-kintone/node_modules/.pnpm/@cybozu+license-manager@1.2.1/node_modules/@cybozu/license-manager/dist/functions/getLicenseText.js:14:15)
    at /home/runner/work/cli-kintone/cli-kintone/node_modules/.pnpm/@cybozu+license-manager@1.2.1/node_modules/@cybozu/license-manager/dist/functions/aggregate.js:21:102
    at Array.map (<anonymous>)
    at aggregate (/home/runner/work/cli-kintone/cli-kintone/node_modules/.pnpm/@cybozu+license-manager@1.2.1/node_modules/@cybozu/license-manager/dist/functions/aggregate.js:18:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async extract (/home/runner/work/cli-kintone/cli-kintone/node_modules/.pnpm/@cybozu+license-manager@1.2.1/node_modules/@cybozu/license-manager/dist/extract.js:18:26)

Node.js v18.20.[3](https://github.com/kintone/cli-kintone/actions/runs/9448860916/job/26023788533#step:7:3)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

_Note_
- [Support for pnpm managed projects](https://github.com/cybozu/license-manager/pull/5)

**Comment by mugi-uno** [comment]
@tuanphamcybozu 
Sorry for the late response.

This issue was caused by a change in pnpm's response format after this update:
https://github.com/pnpm/pnpm/pull/7528

We've fixed this in v1.3.0 to work with the new response format:
https://github.com/cybozu/license-manager/releases/tag/v1.3.0
